### PR TITLE
Use GITHUB_TOKEN if available

### PR DESCRIPTION
**Pull request by danielbayley**
Some other packages and tools utilise this environment variable, so get with the program!

### CODE REVIEW

**Review by dkoontz — COMMENTED** [review]
Great point. But could this be reformulated to
`const token = atom.config.get('atom-github-notifications.personalAccessToken') || process.env.GITHUB_TOKEN;`

**Comment by danielbayley** [comment]
@dkoontz Sure, I was looking for the ES6 equivalent of `?` conditional assignment in CoffeeScript but it's lacking in a lot of areas so I ended up just tweaking the output of CS… but that is better 👍

**Review by dkoontz — APPROVED** [review]

**Comment by danielbayley** [comment]
@dkoontz Strangely, I still get the

> GitHub Notifications
You need to add a Personal Access Token to get notifications from GitHub
Go add one

notification with every new Atom window no matter what… even though
~~~ js
const token = '' || process.env.GITHUB_TOKEN; // Empty string replicates no config setting…
if (!token) { console.log('no token') } else { console.log(token) }
~~~
logs the token.

**Comment by danielbayley** [comment]
I should add that the notifications from GitHub do show up as intended (so the `GITHUB_TOKEN` is obviously being picked up)… just that the initial notification shouldn't, but does.

**Pull request merged**
